# Это сделано через uue, так как я вначале не знал, как хранить в cvs
# нетекстовые (не ASCII) бинарные файлы

all:    pklite.uue cs0.uue cc0.uue
        uudecode pklite.uue
        uudecode cs0.uue
        uudecode cc0.uue

