char *sys_errlist[] =
{
/* EZERO    0 */ "Error 0 - no error",
/* EINVFNC  1 */ "Invalid function number",
/* ENOENT   2 */ "No such file or directory",
/* ENOPATH  3 */ "Path not found",
/* EMFILE   4 */ "Too many open files",
/* EACCES   5 */ "Permission denied",
/* EBADF    6 */ "Bad file number",
/* ECONTR   7 */ "Memory blocks destroyed",
/* ENOMEM   8 */ "Not enough core",
/* EINVMEM  9 */ "Invalid memory block address",
/* EINVENV 10 */ "Invalid environment",
/* EINVFMT 11 */ "Invalid format",
/* EINVACC 12 */ "Invalid access code",
/* EINVDAT 13 */ "Invalid data",
/*         14 */ "Unknown error",
/* ENODEV  15 */ "No such device",
/* ECURDIR 16 */ "Attempt to remove CurDir",
/* ENOTSAM 17 */ "Not same device",
/* ENMFILE 18 */ "No more files",
/* EINVAL  19 */ "Invalid argument",
/* E2BIG   20 */ "Arg list too long",
/* ENOEXEC 21 */ "Exec format error",
/* EXDEV   22 */ "Cross-device link",
/*         23 */ "Unknown error",
/*         24 */ "Unknown error",
/*         25 */ "Unknown error",
/*         26 */ "Unknown error",
/*         27 */ "Unknown error",
/*         28 */ "Unknown error",
/*         29 */ "Unknown error",
/*         30 */ "Unknown error",
/*         31 */ "Unknown error",
/*         32 */ "Unknown error",
/* EDOM    33 */ "Math argument",
/* ERANGE  34 */ "Result too large",
/* EEXIST  35 */ "File already exists",
/* EFAULT  36 */ "Unknown error",
/* EPERM   37 */ "Unknown error",
/* ESRCH   38 */ "Unknown error",
/* EINTR   39 */ "Unknown error",
/* EIO     40 */ "Unknown error",
/* ENXIO   41 */ "Unknown error",
/* ECHILD  42 */ "Unknown error",
/* EAGAIN  43 */ "Unknown error",
/* ENOTBLK 44 */ "Unknown error",
/* EBUSY   45 */ "Unknown error",
/* ENOTDIR 46 */ "Unknown error",
/* EISDIR  47 */ "Unknown error",
/* ENFILE  48 */ "Unknown error",
/* ENOTTY  49 */ "Unknown error",
/* ETXTBSY 50 */ "Unknown error",
/* EFBIG   51 */ "Unknown error",
/* ENOSPC  52 */ "Unknown error",
/* ESPIPE  53 */ "Unknown error",
/* EROFS   54 */ "Unknown error",
/* EMLINK  55 */ "Unknown error",
/* EPIPE   56 */ "Unknown error",
/* EUCLEAN 57 */ "Unknown error"
};

int sys_nerr = 57;
